spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

server:
  port: 8080
